/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package soplanificacion;



import ProccesFabrication.Process;
// ¡Importa tu Enum ProcessState!
import ProccesFabrication.ProcessState; 

import java.awt.Color;
import javax.swing.border.LineBorder;
/**
 *
 * @author dugla
 */
public class PanelProcesoVista extends javax.swing.JPanel {

    /**
     * Creates new form PanelProcesoVista
     */
    public PanelProcesoVista() {
        
        initComponents();
        this.setBorder(new LineBorder(Color.GRAY, 1));
    }
    
    public void actualizarDatos(Process p) {
        
        // 1. Asigna todos los valores
        lblNombreProceso.setText(p.getName());         // Usa p.getName()
        lblID.setText(String.valueOf(p.getId()));      // Usa p.getId()
        lblEstado.setText(p.getState().toString());    // Usa p.getState()
        lblPC.setText(String.valueOf(p.getProgramCounter())); // Usa p.getProgramCounter()
        lblMAR.setText(String.valueOf(p.getMemoryAddressRegister())); // Usa p.getMemoryAddressRegister()

        // 2. Lógica para el "Tipo"
        if (p.isIsIOBound()) { // Usa p.isIsIOBound()
            lblTipo.setText("I/O Bound");
        } else {
            lblTipo.setText("CPU Bound");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreProceso = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblPC = new javax.swing.JLabel();
        lblMAR = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(150, 170));

        lblNombreProceso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombreProceso.setText("Proceso");
        lblNombreProceso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblNombreProceso.setPreferredSize(new java.awt.Dimension(90, 100));

        jLabel1.setText("ID:");

        jLabel2.setText("Estado:");

        jLabel3.setText("Tipo:");

        jLabel4.setText("PC:");

        jLabel5.setText("MAR:");

        lblID.setText("ID:");

        lblEstado.setText("Estado:");

        lblTipo.setText("Tipo:");

        lblPC.setText("PC:");

        lblMAR.setText("MAR:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPC))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTipo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEstado))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblID))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMAR)))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNombreProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblNombreProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblPC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblMAR))
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMAR;
    private javax.swing.JLabel lblNombreProceso;
    private javax.swing.JLabel lblPC;
    private javax.swing.JLabel lblTipo;
    // End of variables declaration//GEN-END:variables
}
